# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 500)
        MainWindow.setMinimumSize(QtCore.QSize(320, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/calculate_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #202020;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 16pt;\n"
"    font-weight: 500;\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MemoryReg = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MemoryReg.sizePolicy().hasHeightForWidth())
        self.MemoryReg.setSizePolicy(sizePolicy)
        self.MemoryReg.setMinimumSize(QtCore.QSize(0, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(62)
        self.MemoryReg.setFont(font)
        self.MemoryReg.setStyleSheet("font-size: 11pt;\n"
"color: #909090;\n"
"margin-right: 7px;")
        self.MemoryReg.setScaledContents(False)
        self.MemoryReg.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.MemoryReg.setObjectName("MemoryReg")
        self.gridLayout_2.addWidget(self.MemoryReg, 1, 1, 1, 1)
        self.EnterReg = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnterReg.sizePolicy().hasHeightForWidth())
        self.EnterReg.setSizePolicy(sizePolicy)
        self.EnterReg.setMinimumSize(QtCore.QSize(0, 80))
        self.EnterReg.setMaxLength(256)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(62)
        self.EnterReg.setFont(font)
        self.EnterReg.setStyleSheet("font-size: 38pt;\n"
"border: none;\n"
"margin-right: 7px;\n"
"")
        self.EnterReg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EnterReg.setReadOnly(True)
        self.EnterReg.setObjectName("EnterReg")
        self.gridLayout_2.addWidget(self.EnterReg, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(4, 4, 5, 5)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_opposite = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_opposite.sizePolicy().hasHeightForWidth())
        self.btn_opposite.setSizePolicy(sizePolicy)
        self.btn_opposite.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 11pt;\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_opposite.setObjectName("btn_opposite")
        self.gridLayout.addWidget(self.btn_opposite, 1, 0, 1, 1)
        self.btn_persent = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_persent.sizePolicy().hasHeightForWidth())
        self.btn_persent.setSizePolicy(sizePolicy)
        self.btn_persent.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 12pt;\n"
"    font-weight: 400;\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_persent.setObjectName("btn_persent")
        self.gridLayout.addWidget(self.btn_persent, 0, 0, 1, 1)
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_7.sizePolicy().hasHeightForWidth())
        self.btn_7.setSizePolicy(sizePolicy)
        self.btn_7.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_7.setObjectName("btn_7")
        self.gridLayout.addWidget(self.btn_7, 2, 0, 1, 1)
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_1.sizePolicy().hasHeightForWidth())
        self.btn_1.setSizePolicy(sizePolicy)
        self.btn_1.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_1.setObjectName("btn_1")
        self.gridLayout.addWidget(self.btn_1, 4, 0, 1, 1)
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sign.sizePolicy().hasHeightForWidth())
        self.btn_sign.setSizePolicy(sizePolicy)
        self.btn_sign.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_sign.setObjectName("btn_sign")
        self.gridLayout.addWidget(self.btn_sign, 5, 0, 1, 1)
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sub.sizePolicy().hasHeightForWidth())
        self.btn_sub.setSizePolicy(sizePolicy)
        self.btn_sub.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_sub.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Icons/remove_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sub.setIcon(icon1)
        self.btn_sub.setObjectName("btn_sub")
        self.gridLayout.addWidget(self.btn_sub, 3, 3, 1, 1)
        self.btn_square = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_square.sizePolicy().hasHeightForWidth())
        self.btn_square.setSizePolicy(sizePolicy)
        self.btn_square.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 11pt;\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_square.setObjectName("btn_square")
        self.gridLayout.addWidget(self.btn_square, 1, 1, 1, 1)
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_3.sizePolicy().hasHeightForWidth())
        self.btn_3.setSizePolicy(sizePolicy)
        self.btn_3.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_3.setObjectName("btn_3")
        self.gridLayout.addWidget(self.btn_3, 4, 2, 1, 1)
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_2.sizePolicy().hasHeightForWidth())
        self.btn_2.setSizePolicy(sizePolicy)
        self.btn_2.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_2.setObjectName("btn_2")
        self.gridLayout.addWidget(self.btn_2, 4, 1, 1, 1)
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_5.sizePolicy().hasHeightForWidth())
        self.btn_5.setSizePolicy(sizePolicy)
        self.btn_5.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_5.setObjectName("btn_5")
        self.gridLayout.addWidget(self.btn_5, 3, 1, 1, 1)
        self.btn_point = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_point.sizePolicy().hasHeightForWidth())
        self.btn_point.setSizePolicy(sizePolicy)
        self.btn_point.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_point.setObjectName("btn_point")
        self.gridLayout.addWidget(self.btn_point, 5, 2, 1, 1)
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_0.sizePolicy().hasHeightForWidth())
        self.btn_0.setSizePolicy(sizePolicy)
        self.btn_0.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_0.setObjectName("btn_0")
        self.gridLayout.addWidget(self.btn_0, 5, 1, 1, 1)
        self.btn_c = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_c.sizePolicy().hasHeightForWidth())
        self.btn_c.setSizePolicy(sizePolicy)
        self.btn_c.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 11pt;\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_c.setObjectName("btn_c")
        self.gridLayout.addWidget(self.btn_c, 0, 2, 1, 1)
        self.btn_sqrt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sqrt.sizePolicy().hasHeightForWidth())
        self.btn_sqrt.setSizePolicy(sizePolicy)
        self.btn_sqrt.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 11pt;\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.gridLayout.addWidget(self.btn_sqrt, 1, 2, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_add.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Icons/add_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon2)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 4, 3, 1, 1)
        self.btn_multiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_multiply.sizePolicy().hasHeightForWidth())
        self.btn_multiply.setSizePolicy(sizePolicy)
        self.btn_multiply.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_multiply.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Icons/close_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_multiply.setIcon(icon3)
        self.btn_multiply.setObjectName("btn_multiply")
        self.gridLayout.addWidget(self.btn_multiply, 2, 3, 1, 1)
        self.btn_ce = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ce.sizePolicy().hasHeightForWidth())
        self.btn_ce.setSizePolicy(sizePolicy)
        self.btn_ce.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 11pt;\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_ce.setObjectName("btn_ce")
        self.gridLayout.addWidget(self.btn_ce, 0, 1, 1, 1)
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_9.sizePolicy().hasHeightForWidth())
        self.btn_9.setSizePolicy(sizePolicy)
        self.btn_9.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_9.setObjectName("btn_9")
        self.gridLayout.addWidget(self.btn_9, 2, 2, 1, 1)
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_6.sizePolicy().hasHeightForWidth())
        self.btn_6.setSizePolicy(sizePolicy)
        self.btn_6.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_6.setObjectName("btn_6")
        self.gridLayout.addWidget(self.btn_6, 3, 2, 1, 1)
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_8.sizePolicy().hasHeightForWidth())
        self.btn_8.setSizePolicy(sizePolicy)
        self.btn_8.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_8.setObjectName("btn_8")
        self.gridLayout.addWidget(self.btn_8, 2, 1, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_divide.sizePolicy().hasHeightForWidth())
        self.btn_divide.setSizePolicy(sizePolicy)
        self.btn_divide.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_divide.setObjectName("btn_divide")
        self.gridLayout.addWidget(self.btn_divide, 1, 3, 1, 1)
        self.btn_backspace = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_backspace.sizePolicy().hasHeightForWidth())
        self.btn_backspace.setSizePolicy(sizePolicy)
        self.btn_backspace.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    background-color: #323232;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b3b3b;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_backspace.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Icons/backspace_white_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_backspace.setIcon(icon4)
        self.btn_backspace.setObjectName("btn_backspace")
        self.gridLayout.addWidget(self.btn_backspace, 0, 3, 1, 1)
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_4.sizePolicy().hasHeightForWidth())
        self.btn_4.setSizePolicy(sizePolicy)
        self.btn_4.setStyleSheet("QPushButton {\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 13pt;\n"
"    background-color: #3b3b3b;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2f2f2f;\n"
"}")
        self.btn_4.setObjectName("btn_4")
        self.gridLayout.addWidget(self.btn_4, 3, 0, 1, 1)
        self.btn_result = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_result.sizePolicy().hasHeightForWidth())
        self.btn_result.setSizePolicy(sizePolicy)
        self.btn_result.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    font-family: \"Segoe Ui Light\";\n"
"    font-size: 16pt;\n"
"    background-color: #76b9ed;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #6da9d8;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #649ac3;\n"
"}")
        self.btn_result.setObjectName("btn_result")
        self.gridLayout.addWidget(self.btn_result, 5, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.MemoryReg.setText(_translate("MainWindow", "55555 ="))
        self.EnterReg.setPlaceholderText(_translate("MainWindow", "0"))
        self.btn_opposite.setText(_translate("MainWindow", "1/𝑥"))
        self.btn_persent.setText(_translate("MainWindow", "%"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_sign.setText(_translate("MainWindow", "+/-"))
        self.btn_square.setText(_translate("MainWindow", "𝑥²"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_point.setText(_translate("MainWindow", ","))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_c.setText(_translate("MainWindow", "C"))
        self.btn_sqrt.setText(_translate("MainWindow", "√𝑥"))
        self.btn_ce.setText(_translate("MainWindow", "CE"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_divide.setText(_translate("MainWindow", "÷"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_result.setText(_translate("MainWindow", "="))
import UIfiles_rc
